name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 128.199.176.121
          username: root
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd /var/www/html/cicd-test2
            git pull origin main
            /root/.nvm/versions/node/v22.5.1/bin/npm install
            /root/.nvm/versions/node/v22.5.1/bin/pm2 restart cicd-demo || /root/.nvm/versions/node/v22.5.1/bin/pm2 start index.js --name cicd-demo
            /root/.nvm/versions/node/v22.5.1/bin/pm2 save
